Project bumicode_erp_stock {
  database_type: 'Laravel'
  Note: '''
    # BUMICODE ERP DB | STOCK 
    **Dokumentasi Database untuk projek ERP dari BUMICODE**  
    - Flow Aplikasi bisa dilihat pada **[Link Ini](https://dbdiagram.io/d/637edb1cc9abfc611174deb0)**  
    - Source Code bisa dilihat di **[Repository Github](https://github.com/bumicode/erp)**  
    - Wiki Aplikasi bisa dilihat di bagian **[Wiki Repository Github](https://github.com/bumicode/erp/wiki)**  
    - Gunakan **[Fitur Diskusi](https://github.com/bumicode/erp/discussions)** untuk berbagi ide dan sebagainya  
    - Riwayat Commit untuk dokumentasi ini bisa dilihat di **[Repository Github](https://github.com/bumicode/dbml/commits/master/bumicode/erp.dbml)**  
      
        
        code with ❤ from sukabumi
  '''
}
