Project bumicode_erp {
  database_type: 'Laravel'
  Note: '''
    # BUMICODE ERP DB
    **Dokumentasi Database untuk projek ERP dari BUMICODE**  
    - Flow Aplikasi bisa dilihat pada **[Link Ini](https://dbdiagram.io/d/637edb1cc9abfc611174deb0)**  
    - Source Code bisa dilihat di **[Repository Github](https://github.com/bumicode/erp)**  
    - Wiki Aplikasi bisa dilihat di bagian **[Wiki Repository Github](https://github.com/bumicode/erp/wiki)**  
    - Gunakan **[Fitur Diskusi](https://github.com/bumicode/erp/discussions)** untuk berbagi ide dan sebagainya  
      
        
        code with ❤ from sukabumi
  '''
}

Table users as U {
  id bigint [pk, increment]
  slug string
  name string
  email string
  email_verified_at timestamptz [null]
  is_active boolean [default: true]
  created_at timestamptz
  updated_at timestamptz
  deleted_at timestamptz
}

Table roles {
  id bigint [pk, increment]
  name string
  description text
  created_at timestamptz
  updated_at timestamptz
  deleted_at timestamptz
}

Table permissions {
  id bigint [pk, increment]
  name string
  description text
  created_at timestamptz
  updated_at timestamptz
  deleted_at timestamptz
}

Table role_has_permission {
  role_id bigint [ref:  <> roles.id]
  permission_id bigint [ref:  <> permissions.id]
}

Table model_has_role {
  user_id bigint [ref: <> users.id]
  role_id bigint [ref: <> roles.id]
}

Table crm.leads {
  id bigint [pk, increment]
  series string [not null]
  saluation bigint [ref: - crm.saluations.id, null]
  job_title string [null]
  lead_owner bigint [ref: - users.id, null]
  gender bigint [ref: - crm.genders.id, null]
  first_name string [not null]
  middle_name string [null]
  last_name string [null]
  lead_source bigint [ref: - crm.lead_sources.id, null]
  status leads_status [null]
  lead_type lead_type [null]
  request_type request_type [null]
  city string [null]
  state string [null]
  country string [null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Enum leads_status {
  "Lead"
  "Open"
  "Replied"
  "Opportunity"
  "Quotation"
  "Lost Quotation"
  "Interested"
  "Converted"
  "Do Not Contact"
}

Enum lead_type {
  "Client"
  "Channel Partner"
  "Consultant"
}

Enum request_type {
  "Product Enquiry"
  "Request for Information"
  "Suggestions"
  "Other"
}

Table crm.lead_sources {
  id bigint [pk, increment]
  name string [not null]
  description text [null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table crm.saluations {
  id bigint [pk, increment]
  name string [not null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table crm.genders {
  id bigint [pk, increment]
  name string [not null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table common.addresses {
  id bigint [pk, increment]
  is_preferred_billing_address boolean [default: 0]
  is_preferred_shipping_address boolean [default: 0]
  is_disabled boolean [default: 0]
  title string [not null]
  address_type address_type [default: "Billing"]
  address_line_one string [not null]
  address_line_two string [null]
  city string [not null]
  district string [null]
  state string [not null]
  country string [null]
  postal_code string [null]
  email_address string [null]
  phone string [null]
  fax string [null]
  tax_category bigint
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Enum address_type {
  "Billing"
  "Shipping"
  "Office"
  "Personal"
  "Plant"
  "Postal"
  "Shop"
  "Subsidiary"
  "Warehouse"
  "Current"
  "Permanent"
  "Other"
}

Table common.addressable [Note: '''
    **Menggunakan [Skema Polymorphic](https://laravel.com/docs/9.x/eloquent-relationships#polymorphic-relationships)**
  '''] {
  id bigint [pk, increment]
  title string [null]
  address_id bigint [ref: > common.addresses.id, not null]
  model_id integer [not null]
  model_type addressable_model_type [not null]
}

Enum addressable_model_type {
  "Lead"
  "Customer"
  "Prospect"
  "Company"
  "Warehouse"
  "Supplier"
  "Driver"
}

Ref: common.addressable.model_id > crm.leads.id
Ref: common.addressable.model_id > crm.prospects.id
Ref: common.addressable.model_id > selling.customers.id
Ref: common.addressable.model_id > company.companies.id
Ref: common.addressable.model_id > stock.warehouses.id
Ref: common.addressable.model_id > buying.suppliers.id
Ref: common.addressable.model_id - common.drivers.id

Table common.contacts {
  id bigint [pk, increment]
  is_primary_contact boolean [default: 0]
  is_billing_contact boolean [default: 0]
  first_name string [not null]
  middle_name string [null]
  last_name string [null]
  email_address string [null]
  user_id bigint [ref: - users.id, null]
  address_id bigint [ref: - common.addressable.id, null]
  status contact_status [default: "Passive"]
  saluation bigint [ref: - crm.saluations.id, null]
  designation string [null]
  gender_id bigint [ref: - crm.genders.id, null]
  mobile_no string [null]
  company_name string [null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Enum contact_status {
  "Passive"
  "Open"
  "Replied"
}

Table common.contactable [Note: '''
    **Menggunakan [Skema Polymorphic](https://laravel.com/docs/9.x/eloquent-relationships#polymorphic-relationships)**
  '''] {
  id bigint [pk, increment]
  title string [null]
  contact_id bigint [ref: > common.contacts.id]
  model_id bigint
  model_type contactable_model_type
}

Enum contactable_model_type {
  "Lead"
  "Customer"
  "Prospect"
  "Company"
  "Warehouse"
  "Supplier"
}

Ref: common.contactable.model_id > crm.leads.id
Ref: common.contactable.model_id > crm.prospects.id
Ref: common.contactable.model_id > selling.customers.id
Ref: common.contactable.model_id > company.companies.id
Ref: common.contactable.model_id > stock.warehouses.id
Ref: common.contactable.model_id > buying.suppliers.id

Table common.emails {
  id bigint [pk, increment]
  email string [not null]
  is_primary boolean [default: 0]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table common.contact_has_email {
  contact_id bigint [ref: <> common.contacts.id]
  email_id bigint [ref: <> common.emails.id]
}

Table common.numbers {
  id bigint [pk, increment]
  number string [not null]
  is_primary_phone boolean [default: 0]
  is_primary_mobile boolean [default: 0]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table common.contact_has_numbers {
  contact_id bigint [ref: > common.contacts.id]
  number_id bigint [ref: - common.numbers.id]
}

Table crm.opportunity {
  id bigint [pk, increment]
  opportunity_date timestamptz [default: `now()`]
  model_id bigint
  model_type opportunity_model_type [Note: "Opportunity From"]
  status opportunity_status
  opportunity_type_id bigint [ref: - crm.opportunity_types.id]
  lead_source_id bigint [ref: - crm.lead_sources.id]
  opportunity_owner_id bigint [ref: - users.id]
  sales_stage_id bigint [ref: - crm.sales_stages.id]
  expected_closing_date date [null]
  probability integer [default: 100]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Enum opportunity_model_type {
  "Lead"
  "Customer"
  "Prospect"
}

Enum opportunity_status {
  "Open"
  "Quotation"
  "Converted"
  "Lost"
  "Replied"
  "Closed"
}

Table crm.opportunity_types {
  id bigint [pk, increment]
  name string [not null]
  description text [null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table crm.sales_stages {
  id bigint [pk, increment]
  name status [not null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table crm.organizations {
  id bigint [pk, increment]
  name string [null]
  no_employees organizations_no_employees [default: "1-10"]
  annual_revenue bigint [null]
  industry bigint [ref: - crm.industries.id]
  market_segment bigint [ref: - crm.market_segments.id]
  territory_id bigint [ref: - selling.territories.id]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Enum organizations_no_employees {
  "1-10"
  "11-50"
  "51-200"
  "201-500"
  "501-1000"
  "1000+"
}

Table crm.industries {
  id bigint [pk, increment]
  name string
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table crm.market_segments {
  id bigint [pk, increment]
  name string
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table crm.organizationable [Note: '''
    **Menggunakan [Skema Polymorphic](https://laravel.com/docs/9.x/eloquent-relationships#polymorphic-relationships)**
  '''] {
  id bigint [pk, increment]
  organizations_id bigint [ref: > crm.organizations.id]
  model_id bigint
  model_type organizationable_model_type
}

Enum organizationable_model_type {
  "Lead"
  "Opportunity"
}

Ref: crm.organizationable.model_id > crm.leads.id
Ref: crm.organizationable.model_id > crm.opportunity.id

Table crm.prospects {
  id bigint [pk, increment]
  customer_group bigint [ref: > selling.customer_groups.id, null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table selling.customers {
  id bigint [pk, increment]
  name string [not null]
  customer_group_id bigint [ref: > selling.customer_groups.id]
  default_company_bank_account bigint [null]
  customer_type customer_type [default: "Individual"]
  territory_id bigint [ref: > selling.territories.id]
  account_manager_id bigint [ref: > public.users.id]
  gender bigint [ref: - crm.genders.id, null]
  allow_sales_invoice_creation_without_sales_order boolean [default: 0]
  allow_sales_invoice_creation_without_delivery_note boolean [default: 0]
  is_internal_customer boolean [default: 0]
  is_disabled boolean [default: 0]
  from_lead_id bigint [ref: - crm.leads.id, null]
  from_opportunity bigint [ref: - crm.opportunity.id, null]
  primary_contact_id bigint [null, ref: - common.contactable.id]
  primary_address_id bigint [null, ref: - common.addressable.id]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Enum selling.customer_type {
  "Company"
  "Individual"
}

Table selling.customer_groups {
  id bigint [pk, increment]
  is_group boolean [default: 0]
  name string [not null]
  parent_id bigint [ref: > selling.customer_groups.id, null]
  default_price_list_id bigint [ref: > stock.price_lists.id, null]
  default_payment_terms_template bigint [ref: > accounting.payment_terms_templates.id, null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table selling.credit_limits {
  id bigint [pk, increment]
  customer_group_id bigint [ref: - selling.customer_groups.id]
  credit_limit bigint
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table stock.price_lists {
  id bigint [pk, increment]
  name string [not null]
  is_buying boolean [default: 0]
  is_selling boolean [default: 0]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table stock.items {
  id bigint [pk, increment]
  is_disabled boolean [default: 0]
  is_maintain_stock boolean [default: 1]
  is_has_variant boolean [default: 0]
  brand_id bigint [ref: > stock.brands.id]
  variant_of bigint [ref: > stock.items.id, null]
  code string [not null]
  name string [null]
  status item_status [null]
  item_group_id bigint [ref: > stock.item_groups.id]
  default_uom bigint [ref: - stock.item_has_oums.id]
  description text [null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Enum item_status {
  "Variant"
  "Template"
}

Table stock.item_groups {
  id bigint [pk, increment]
  name string [not null]
  parent_id bigint [ref: > stock.item_groups.id]
  is_group boolean [default: 0]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table stock.uoms {
  id bigint [pk, increment]
  is_enable boolean [default: 1]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table stock.warehouses {
  id bigint [pk, increment]
  is_disabled boolean [default: 0]
  is_group boolean [default: 0]
  warehouse_type_id bigint [ref: > stock.warehouse_types.id, null]
  name string [not null]
  parent_id bigint [ref: > stock.warehouses.id, null]
  warehouse_account bigint [Note: "REFERENCE NOT SET", null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table stock.warehouse_types {
  id bigint [pk, increment]
  name string [not null]
  description text [null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table stock.brands {
  id bigint [pk, increment]
  name string [not null]
  description text [null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table stock.item_attributes {
  id bigint [pk, increment]
  name string [not null]
  value array [not null, Note: '''
    [
      {
        value: "Red",
        abb: RED
      }, {
        value: Green,
        abb: GRE
      }
    ]
  ''']
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table stock.item_has_attributes {
  item_id bigint [ref: <> stock.items.id, not null]
  item_attribute_id bigint [ref: <> stock.item_attributes.id, not null]
}

Table stock.item_prices {
  id bigint [pk, increment]
  is_buying boolean [default: 0]
  is_selling boolean [default: 0]
  item_id bigint [ref: > stock.items.id, not null]
  item_uom_id bigint [ref: > stock.item_has_oums.id, not null]
  packing_unit integer [default: 0]
  price_list_id bigint [ref: > stock.price_lists.id]
  batch_no bigint [Note: "REFERENCE NOT SET"]
  rate bigint [Note: "Harga"]
  valid_from timestamptz [default: `now()`]
  valid_upto timestamptz [null]
  note text [null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table stock.priceable [Note: '''
    **Menggunakan [Skema Polymorphic](https://laravel.com/docs/9.x/eloquent-relationships#polymorphic-relationships)**
  '''] {
  item_price_id bigint [ref: - stock.item_prices.id]
  model_id bigint
  model_type model_priceable
}

Table stock.product_bundles [Note: "Bundle Item"] {
  id bigint [pk, increment]
  parent_item_id bigint [ref: > stock.items.id]
  description text [null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table stock.packing_lists [Note: "Product Bundle Has Items"] {
  product_bundles_id bigint [ref: <> stock.product_bundles.id]
  item_id bigint [ref: <> stock.items.id]
}

Table stock.material_requests {
  id bigint [pk, increment]
  series string [not null]
  purpose material_request_type
  transaction_date timestamptz [default: `now()`]
  required_by timestamptz [null]
  warehouse_target_id bigint [ref: > stock.warehouses.id, null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table stock.material_request_has_item {
  id bigint [pk, increment]
  material_request_id bigint [ref: > stock.material_requests.id, not null]
  item_id bigint [ref: > stock.items.id, not null]
  required_by timestamptz [not null]
  qty integer [not null]
  warehouse_target_id bigint [ref: > stock.warehouses.id, null]
  item_uom_id bigint [ref: > stock.item_has_oums.id, not null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table stock.stock_entries {
  id bigint [pk, increment]
  stock_entry_type bigint [ref: > stock.entry_types.id, not null]
  posting_date timestamptz [default: `now()`]
  warehouse_source_id bigint [ref: > stock.warehouses.id, null]
  total_outgoing_value bigint [not null]
  total_incoming_value bigint [not null]
  total_value bigint [Note: "Incoming - Outgoing", not null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table stock.stock_entrie_has_item {
  id bigint [pk, increment]
  stock_entrie_id bigint [ref: > stock.stock_entries.id, not null]
  item_id bigint [ref: > stock.items.id, not null]
  warehouse_target_id bigint [ref: > stock.warehouses.id, not null]
  warehouse_source_id bigint [ref: > stock.warehouses.id, null]
  qty integer [not null]
  item_uom_id bigint [ref: > stock.item_has_oums.id, not null]
  basic_rate bigint [Note: "Basic Rate as per stock UOM"]
  basic_amount bigint [Note: "Qty x Basic Rate"]
  additional_cost bigint [default: 0]
  amount bigint [default: 0]
  valuation_rate bigint [default: 0]
  account_id bigint [Note: "REFERENCE NOT SET"]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table stock.entry_types {
  id bigint [pk, increment]
  name string [not null]
  purpose entry_type_purpose [not null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Enum entry_type_purpose {
  "Material Issue"
  "Material Receipt"
  "Material Transfer"
  "Material Transfer for Manufacture"
  "Material Consumption for Manufacture"
  "Manufacture"
  "Repack"
  "Send to Subcontractor"
}

Table stock.delivery_notes {
  id bigint [pk, increment]
  status delivery_note_status [default: "Draft"]
  customer_id bigint [ref: > selling.customers.id]
  posting_date timestamptz [default: `now()`]
  address_id bigint [ref: > common.addressable.id, not null]
  contact_id bigint [ref: > common.contactable.id, not null]
  total_qty integer [not null]
  total_net_weight integer [not null]
  total_amount bigint [not null]
  tax_category bigint [Note: "REFERENCE NOT SET"]
  sales_tax_charge_template bigint [Note: "REFERENCE NOT SET"]
  total_tax_charge bigint [not null]
  grand_total bigint [not null]
  rounding_adjustment bigint [null]
  rounded_total bigint [null]
  transporter_id bigint [ref: > buying.suppliers.id, Note: "Supplier is Transporter"]
  driver_id bigint [ref: > common.drivers.id]
  transport_receipt_no string [null]
  transport_receipt_date timestamptz
  vehincle_no string [null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Enum delivery_note_status {
  "Draft"
  "To Bill"
  "Completed"
  "Return Issued"
  "Cancelled"
  "Closed"
}

Table common.drivers {
  id bigint [pk, increment]
  series string [not null, Note: "Auto Generated"]
  full_name string [not null]
  status driver_status [Note: "Simple is Active or Not Active"]
  transporter_id bigint [ref: > buying.suppliers.id, Note: "Supplier is Transporter"]
  cellphone_number string
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Enum driver_status {
  "Active"
  "Suspend"
  "Left"
}

Table stock.delivery_note_has_items {
  id bigint [pk, increment]
  delivery_note_id bigint [ref: > stock.delivery_notes.id, not null]
  item_id bigint [ref: > stock.items.id, not null]
  qty integer [not null]
  item_uom_id bigint [ref: > stock.item_has_oums.id]
  rate integer [not null]
  amount integer [not null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table stock.delivery_note_has_taxes {
  id bigint [pk, increment]
  type tax_and_charge  [not null]
  account_id bigint [Note: "REFERENCE NOT SET"]
  rate integer [default: 0]
  amount bigint [default: 0]
  total bigint [default: 0]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Enum tax_and_charge {
  "Actual"
  "On Net Total"
  "On Previous Row Amount"
  "On Previous Row Total"
  "On Item Quantity"
}

Table accounting.pricing_rules {
  id bigint [pk, increment]
  is_disabled boolean [default: 0]
  series string [not null, Note: "Auto Generate"]
  title string [not null]
  rules_for pricing_rules [default: "Item Code"]
  discount_type pricing_rule_discount_type
  warehouse_id bigint [ref: > stock.warehouses.id, null]
  pricing_rule_target pricing_rule_target
  min_qty integer [default: 0]
  max_qty integer [null]
  min_amt bigint [default: 0]
  max_amt bigint [null]
  valid_from timestamptz [default: `now()`]
  valid_upto timestamptz [null]
  margin_type margin_type [default: "Percentage"] 
  margin bigint [default: 0, Note: "Percentage in %, Amount in number"]
  discount_scheme_type discount_scheme_type 
  discount bigint [default: 0, Note: "Percentage in %, Amount and Rate in number"]
  priority integer [default: 1, Note: "Higher number higher priority"]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Enum discount_scheme_type {
  "Rate"
  "Discount Percentage"
  "Discount Amount"
}

Enum margin_type {
  "Percentage"
  "Amount"
}

Table accounting.pricing_rule_targetable [Note: '''
    **Menggunakan [Skema Polymorphic](https://laravel.com/docs/9.x/eloquent-relationships#polymorphic-relationships)**
  '''] {
  pricing_rule_id bigint [ref: > accounting.pricing_rules.id]
  model_id bigint
  model_type pricing_rule_targetable_model
}

Enum pricing_rule_targetable_model {
  "Seliing:Customer"
  "Selling:Customer Group"
  "Selling:Territorie"
  "Selling:Sales Partner"
  "Selling:Campaign"
  "Buying:Supplier"
  "Buying:Supplier Group"
}

Enum pricing_rule_target {
  "Selling"
  "Buying"
}

Enum pricing_rule_discount_type {
  "Price"
  "Product"
}

Enum pricing_rules {
  "Item Code"
  "Item Group"
  "Brand"
  "Transaction"
}

Table accounting.applied_rules [Note: '''
    **Menggunakan [Skema Polymorphic](https://laravel.com/docs/9.x/eloquent-relationships#polymorphic-relationships)**
  '''] {
  pricing_rule_id bigint [ref: > accounting.pricing_rules.id]
  model_id bigint
  model_type applied_rules_model
  uom_item_id bigint [ref: > stock.item_has_oums.id]
}

Enum applied_rules_model {
  "Item"
  "Item Group"
  "Brand"
}

Ref: accounting.applied_rules.model_id > stock.items.id
Ref: accounting.applied_rules.model_id > stock.item_groups.id
Ref: accounting.applied_rules.model_id > stock.brands.id

Enum model_priceable {
  "Customer"
  "Supplier"
}

Ref: stock.priceable.model_id > selling.customers.id
Ref: stock.priceable.model_id > buying.suppliers.id

Table buying.suppliers {
  id bigint [pk, increment]
  name string [not null]
  supplier_group_id bigint [ref: > buying.supplier_groups.id]
  supplier_type supplier_type [default: "Company"]
  allow_purchase_invoice_without_purchase_order boolean [default: 0]
  allow_purchase_invoice_without_purchase_receipt boolean [default: 0]
  is_transporter boolean [default: 0]
  primary_address_id bigint [ref: - common.addressable.id]
  primary_contact_id bigint [ref: - common.contactable.id]
  website string [null]
  details text [null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Enum supplier_type {
  "Company"
  "Individual"
}

Table buying.supplier_groups {
  id bigint [pk, increment]
  is_group boolean [default: 0]
  name string [not null]
  description text [null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table stock.item_inventories {
  id bigint [pk, increment]
  item_id bigint [ref: - stock.items.id, not null]
  shelf_life_in_days integer [null]
  warranty_period integer [null]
  end_of_life timestamptz [not null]
  weight_per_unit integer [null]
  weight_uom bigint [ref: - stock.item_has_oums.id, Note: "Default UOM Item"]
  default_material_request_type material_request_type [default: "Purchase"]
  valuation_method valuation_method [default: "", null]
  allow_negative_stock boolean [default: 0]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Enum material_request_type {
  "Purchase"
  "Material Transfer"
  "Material Issue"
  "Manufacture"
  "Customer Provided"
}

Enum valuation_method {
  "FIFO"
  "Moving Average"
  "LIFO"
}

Table stock.item_has_oums {
  id bigint [pk, increment]
  is_default boolean [default: 0]
  item_id bigint [ref: > stock.items.id, not null]
  uom_id bigint [ref: > stock.uoms.id, not null]
  conversion_factor integer
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table stock.item_barcodes {
  id bigint [pk, increment]
  item_id bigint [ref: > stock.items.id, not null]
  uom_id bigint [ref: > stock.item_has_oums.id, not null]
  barcode string [not null]
  barcode_type barcode_type [not null] 
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Enum barcode_type {
  "EAN"
  "UPC-A"
}

Table stock.shipments {
  id bigint [pk, increment]
  series string [Note: "Auto Generated"]
  status shipment_status [default: "Draft"]
  shipment_type shipment_type [default: "Goods"]
  value_of_goods bigint [not null]
  pickup_type pickup_type [default: "Pickup"]
  pickup_date timestamptz [not null]
  pickup_from timestamptz [Note: "Start time pickup", not null]
  pickup_to timestamptz [Note: "End time pickup", not null]
  description_content text [not null]
  service_provider string [null]
  carrier_id bigint [ref: > common.carriers.id, null]
  carrier_service_id bigint [ref: > common.carrier_services.id, null]
  awb_number string [null]
  shipment_amount bigint [null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Enum shipment_status {
  "Draft"
  "Submited"
  "Booked"
  "Cancelled"
  "Completed"
}

Table common.carriers {
  id bigint [pk, increment]
  name string [not null]
  abb string [not null, Note: "Only Character"]
  description text [null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table common.carrier_services {
  id bigint [pk, increment]
  carriers_id bigint [ref: - common.carriers.id]
  name string [not null]
  abb string [not null, Note: "Only Character"]
  description text [null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Enum pickup_type {
  "Pickup"
  "Self Delivery"
}

Enum shipment_type {
  "Goods"
  "Documents"
}

Table stock.pickupable [Note: '''
    **Menggunakan [Skema Polymorphic](https://laravel.com/docs/9.x/eloquent-relationships#polymorphic-relationships)**
  '''] {
  shipment_id bigint [ref: > stock.shipments.id]
  model_id bigint
  model_type shippable_model
  addressable_id bigint [ref: > common.addressable.id]
  contactable_id bigint [ref: > common.contactable.id]
}

Table stock.deliveryable [Note: '''
    **Menggunakan [Skema Polymorphic](https://laravel.com/docs/9.x/eloquent-relationships#polymorphic-relationships)**
  '''] {
  shipment_id bigint [ref: > stock.shipments.id]
  model_id bigint
  model_type shippable_model
  addressable_id bigint [ref: > common.addressable.id]
  contactable_id bigint [ref: > common.contactable.id]
}

Enum shippable_model {
  "Company"
  "Customer"
  "Supplier"
}

Table accounting.payment_terms_templates {
  id bigint [pk, increment]
  name string [not null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table accounting.payment_terms_template_has_payment_terms {
  payment_terms_template_id bigint [ref: <> accounting.payment_terms_templates.id, not null]
  payment_term_id bigint [ref: <> accounting.payment_terms.id, not null]
}

Table accounting.payment_terms {
  id bigint [pk, increment]
  name string [not null]
  invoice_portion integer
  due_date_base due_date_base [default: "Day(s) after invoice date"]
  credit_days integer [not null, default: 0]
  description text [null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Enum due_date_base {
  "Day(s) after invoice date"
  "Day(s) after the end of the invoice month"
  "Month(s) after the end of the invoice month"
}

Table company.companies {
  id bigint [pk, increment]
  name string [not null]
  parent_id bigint [ref: < company.companies.id]
  is_group boolean [default: 0]
  description text [null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table company.settings {
  id bigint [pk, increment]
}

Table selling.territories {
  id bigint [pk, increment]
  parent_id bigint [ref: > selling.territories.id, null]
  territory_manager_id bigint [ref: > selling.sales_persons.id]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table selling.sales_persons {
  id bigint [pk, increment]
  is_group boolean [default: 0]
  is_enable boolean [default: 1]
  name string [not null]
  employee bigint [Note: "REFERENCE NOT SET"]
  parent_id bigint [ref: > selling.sales_persons.id]
  commision_rate integer [null]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table selling.sales_person_has_targets {
  sales_person_id bigint [ref: - selling.sales_persons.id]
  item_group_target_id bigint [Note: "REFERENCE NOT SET"]
  fiscal_year_id bigint [Note: "REFERENCE NOT SET"]
  target_qty integer [default: 0]
  target_amount bigint [default: 0]
  target_distribution_id bigint [Note: "REFERENCE NOT SET"]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table selling.territory_has_targets {
  sales_person_id bigint [ref: - selling.territories.id]
  item_group_target_id bigint [Note: "REFERENCE NOT SET"]
  fiscal_year_id bigint [Note: "REFERENCE NOT SET"]
  target_qty integer [default: 0]
  target_amount bigint [default: 0]
  target_distribution_id bigint [Note: "REFERENCE NOT SET"]
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}

Table common.status [Note: "Opsional bila status dimasukkan kedalam database"] {
  id bigint [pk, increment]
  name string
  model_id bigint
  model_type string
  created_at timestamptz [default: `now()`]
  edited_at timestamptz [default: `now()`]
  deleted_at timestamptz [null]
}
